version: "3"

services:
  fastapi:
    env_file:
      - .env
    container_name: fastapi
    networks:
      data-lake-network:
    build:
      context: fastapi/.
      dockerfile: Dockerfile
    volumes:
      - ./fastapi/:/code
    ports:
      - 8080:8080
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      data-lake-network:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      data-lake-network:
        aliases:
          - minio.minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/source-bucket;
      /usr/bin/mc policy set public minio/source_bucket;
      "


networks:
  data-lake-network: 
